version: "3.2"

services:
  teacos-mysql:
    image: mysql:latest
    networks:
     - mmvib-net
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-storage:

networks:
  mmvib-net:
    external: true
