version: "3.8"

services:
  mmvib-teacos-adapter:
    build: .
    image: mmvib-teacos-adapter:dev
    volumes:
      - .:/code
    command: ["gunicorn", "--reload", "tno.aimms_adapter.main:app", "-t 300", "-w 1", "-b :9204"]
    ports:
      - "9204:9204"
    env_file:
      - ".env.docker"
    networks:
      - mmvib-net

  teacos-mysql:
    image: mysql:8.0-debian
    networks:
      - mmvib-net
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  adminer:
    image: adminer:4-standalone
    ports:
      - "8081:8080"
    networks:
      - mmvib-net

volumes:
  mysql-storage:

networks:
  mmvib-net:
    driver: bridge
    external: true
    name: mmvib-net
