version: "3.2"

services:
  mmvib-teacos-adapter:
    build: .
    image: mmvib-teacos-adapter:dev
    volumes:
      - .:/code
    command: ["gunicorn", "--reload", "tno.aimms_adapter.main:app", "-t 300", "-w 1", "-b :9204"]
    ports:
      - "9204:9204"
    env_file:
      - ".env.docker"
    networks:
      - mmvib-net

  teacos-mysql:
    image: mysql:latest
    networks:
     - mmvib-net
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

volumes:
  mysql-storage:

networks:
  mmvib-net:
    external: true
