version: "3.8"

services:
  teacos-mysql:
    image: mysql:latest
    networks:
     - mmvib-net
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  mysql-storage:

networks:
  mmvib-net:
    driver: bridge
    external: true
    name: mmvib-net
